# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_settings.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogSettings(object):
    def setupUi(self, DialogSettings):
        DialogSettings.setObjectName("DialogSettings")
        DialogSettings.setModal(False)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DialogSettings)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gbSampling = QtWidgets.QGroupBox(DialogSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbSampling.sizePolicy().hasHeightForWidth())
        self.gbSampling.setSizePolicy(sizePolicy)
        self.gbSampling.setObjectName("gbSampling")
        self.glDataCollection = QtWidgets.QGridLayout(self.gbSampling)
        self.glDataCollection.setObjectName("glDataCollection")
        self.labelGuiRate = QtWidgets.QLabel(self.gbSampling)
        self.labelGuiRate.setObjectName("labelGuiRate")
        self.glDataCollection.addWidget(self.labelGuiRate, 2, 1, 1, 1)
        self.sbSampleRate = QtWidgets.QSpinBox(self.gbSampling)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbSampleRate.sizePolicy().hasHeightForWidth())
        self.sbSampleRate.setSizePolicy(sizePolicy)
        self.sbSampleRate.setMinimumSize(QtCore.QSize(80, 0))
        self.sbSampleRate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbSampleRate.setObjectName("sbSampleRate")
        self.glDataCollection.addWidget(self.sbSampleRate, 0, 2, 1, 1)
        self.leGuiUpdateRate = QtWidgets.QLineEdit(self.gbSampling)
        self.leGuiUpdateRate.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leGuiUpdateRate.sizePolicy().hasHeightForWidth())
        self.leGuiUpdateRate.setSizePolicy(sizePolicy)
        self.leGuiUpdateRate.setMinimumSize(QtCore.QSize(80, 0))
        self.leGuiUpdateRate.setMaximumSize(QtCore.QSize(80, 16777215))
        self.leGuiUpdateRate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.leGuiUpdateRate.setObjectName("leGuiUpdateRate")
        self.glDataCollection.addWidget(self.leGuiUpdateRate, 2, 2, 1, 1)
        self.labelSampleRate = QtWidgets.QLabel(self.gbSampling)
        self.labelSampleRate.setObjectName("labelSampleRate")
        self.glDataCollection.addWidget(self.labelSampleRate, 0, 1, 1, 1)
        self.sbDumpRate = QtWidgets.QSpinBox(self.gbSampling)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbDumpRate.sizePolicy().hasHeightForWidth())
        self.sbDumpRate.setSizePolicy(sizePolicy)
        self.sbDumpRate.setMinimumSize(QtCore.QSize(80, 0))
        self.sbDumpRate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbDumpRate.setObjectName("sbDumpRate")
        self.glDataCollection.addWidget(self.sbDumpRate, 1, 2, 1, 1)
        self.labelDumpRate = QtWidgets.QLabel(self.gbSampling)
        self.labelDumpRate.setObjectName("labelDumpRate")
        self.glDataCollection.addWidget(self.labelDumpRate, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.gbSampling)
        self.gbXAxis = QtWidgets.QGroupBox(DialogSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbXAxis.sizePolicy().hasHeightForWidth())
        self.gbXAxis.setSizePolicy(sizePolicy)
        self.gbXAxis.setMaximumSize(QtCore.QSize(16777215, 170))
        self.gbXAxis.setObjectName("gbXAxis")
        self.glXAxis = QtWidgets.QGridLayout(self.gbXAxis)
        self.glXAxis.setObjectName("glXAxis")
        self.labelXAxisLength = QtWidgets.QLabel(self.gbXAxis)
        self.labelXAxisLength.setObjectName("labelXAxisLength")
        self.glXAxis.addWidget(self.labelXAxisLength, 0, 0, 1, 1)
        self.sbLenAxisX = QtWidgets.QSpinBox(self.gbXAxis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbLenAxisX.sizePolicy().hasHeightForWidth())
        self.sbLenAxisX.setSizePolicy(sizePolicy)
        self.sbLenAxisX.setMinimumSize(QtCore.QSize(80, 0))
        self.sbLenAxisX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbLenAxisX.setObjectName("sbLenAxisX")
        self.glXAxis.addWidget(self.sbLenAxisX, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.gbXAxis)
        self.bbApplyClose = QtWidgets.QDialogButtonBox(DialogSettings)
        self.bbApplyClose.setOrientation(QtCore.Qt.Horizontal)
        self.bbApplyClose.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Close)
        self.bbApplyClose.setObjectName("bbApplyClose")
        self.verticalLayout_2.addWidget(self.bbApplyClose)

        self.retranslateUi(DialogSettings)
        self.bbApplyClose.accepted.connect(DialogSettings.accept)
        self.bbApplyClose.rejected.connect(DialogSettings.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogSettings)

    def retranslateUi(self, DialogSettings):
        _translate = QtCore.QCoreApplication.translate
        DialogSettings.setWindowTitle(_translate("DialogSettings", "Oscilloscope Settings"))
        self.gbSampling.setTitle(_translate("DialogSettings", "Data Collection"))
        self.labelGuiRate.setText(_translate("DialogSettings", "GUI Update Rate [ms]"))
        self.labelSampleRate.setText(_translate("DialogSettings", "Sample Rate [ms]"))
        self.labelDumpRate.setText(_translate("DialogSettings", "Dump Rate [samples/dump]"))
        self.gbXAxis.setTitle(_translate("DialogSettings", "X-axis"))
        self.labelXAxisLength.setText(_translate("DialogSettings", "Default Length [sec]"))
