# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_main.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WindowMain(object):
    def setupUi(self, WindowMain):
        WindowMain.setObjectName("WindowMain")
        WindowMain.resize(892, 538)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("IcepapCfg Icons/gnome-monitor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WindowMain.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(WindowMain)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.hloAll = QtWidgets.QHBoxLayout()
        self.hloAll.setObjectName("hloAll")
        self.vloControls = QtWidgets.QVBoxLayout()
        self.vloControls.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.vloControls.setObjectName("vloControls")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelDrivers = QtWidgets.QLabel(self.centralwidget)
        self.labelDrivers.setMaximumSize(QtCore.QSize(57, 16777215))
        self.labelDrivers.setObjectName("labelDrivers")
        self.horizontalLayout_3.addWidget(self.labelDrivers)
        self.labelSignals = QtWidgets.QLabel(self.centralwidget)
        self.labelSignals.setMaximumSize(QtCore.QSize(137, 16777215))
        self.labelSignals.setObjectName("labelSignals")
        self.horizontalLayout_3.addWidget(self.labelSignals)
        self.vloControls.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cbDrivers = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbDrivers.sizePolicy().hasHeightForWidth())
        self.cbDrivers.setSizePolicy(sizePolicy)
        self.cbDrivers.setMaximumSize(QtCore.QSize(57, 16777215))
        self.cbDrivers.setObjectName("cbDrivers")
        self.horizontalLayout_2.addWidget(self.cbDrivers)
        self.cbSignals = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbSignals.sizePolicy().hasHeightForWidth())
        self.cbSignals.setSizePolicy(sizePolicy)
        self.cbSignals.setMaximumSize(QtCore.QSize(137, 16777215))
        self.cbSignals.setObjectName("cbSignals")
        self.horizontalLayout_2.addWidget(self.cbSignals)
        self.vloControls.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setMaximumSize(QtCore.QSize(200, 16777215))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.vloControls.addWidget(self.line)
        self.hloAxes = QtWidgets.QHBoxLayout()
        self.hloAxes.setObjectName("hloAxes")
        self.labelAxis = QtWidgets.QLabel(self.centralwidget)
        self.labelAxis.setObjectName("labelAxis")
        self.hloAxes.addWidget(self.labelAxis)
        self.rbAxis1 = QtWidgets.QRadioButton(self.centralwidget)
        self.rbAxis1.setObjectName("rbAxis1")
        self.hloAxes.addWidget(self.rbAxis1)
        self.rbAxis2 = QtWidgets.QRadioButton(self.centralwidget)
        self.rbAxis2.setObjectName("rbAxis2")
        self.hloAxes.addWidget(self.rbAxis2)
        self.rbAxis3 = QtWidgets.QRadioButton(self.centralwidget)
        self.rbAxis3.setObjectName("rbAxis3")
        self.hloAxes.addWidget(self.rbAxis3)
        self.vloControls.addLayout(self.hloAxes)
        self.btnAdd = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAdd.sizePolicy().hasHeightForWidth())
        self.btnAdd.setSizePolicy(sizePolicy)
        self.btnAdd.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnAdd.setObjectName("btnAdd")
        self.vloControls.addWidget(self.btnAdd)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelRemove = QtWidgets.QLabel(self.centralwidget)
        self.labelRemove.setMaximumSize(QtCore.QSize(60, 16777215))
        self.labelRemove.setObjectName("labelRemove")
        self.horizontalLayout.addWidget(self.labelRemove)
        self.btnRemoveSel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRemoveSel.sizePolicy().hasHeightForWidth())
        self.btnRemoveSel.setSizePolicy(sizePolicy)
        self.btnRemoveSel.setMaximumSize(QtCore.QSize(82, 16777215))
        self.btnRemoveSel.setObjectName("btnRemoveSel")
        self.horizontalLayout.addWidget(self.btnRemoveSel)
        self.btnRemoveAll = QtWidgets.QPushButton(self.centralwidget)
        self.btnRemoveAll.setMaximumSize(QtCore.QSize(46, 16777215))
        self.btnRemoveAll.setObjectName("btnRemoveAll")
        self.horizontalLayout.addWidget(self.btnRemoveAll)
        self.vloControls.addLayout(self.horizontalLayout)
        self.lvActiveSig = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lvActiveSig.sizePolicy().hasHeightForWidth())
        self.lvActiveSig.setSizePolicy(sizePolicy)
        self.lvActiveSig.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lvActiveSig.setObjectName("lvActiveSig")
        self.vloControls.addWidget(self.lvActiveSig)
        self.btnShift = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnShift.sizePolicy().hasHeightForWidth())
        self.btnShift.setSizePolicy(sizePolicy)
        self.btnShift.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnShift.setObjectName("btnShift")
        self.vloControls.addWidget(self.btnShift)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vloControls.addItem(spacerItem)
        self.btnCLoop = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCLoop.sizePolicy().hasHeightForWidth())
        self.btnCLoop.setSizePolicy(sizePolicy)
        self.btnCLoop.setMaximumSize(QtCore.QSize(200, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.btnCLoop.setPalette(palette)
        self.btnCLoop.setObjectName("btnCLoop")
        self.vloControls.addWidget(self.btnCLoop)
        self.btnCurrents = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCurrents.sizePolicy().hasHeightForWidth())
        self.btnCurrents.setSizePolicy(sizePolicy)
        self.btnCurrents.setMaximumSize(QtCore.QSize(200, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.btnCurrents.setPalette(palette)
        self.btnCurrents.setObjectName("btnCurrents")
        self.vloControls.addWidget(self.btnCurrents)
        self.btnTarget = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTarget.sizePolicy().hasHeightForWidth())
        self.btnTarget.setSizePolicy(sizePolicy)
        self.btnTarget.setMaximumSize(QtCore.QSize(200, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.btnTarget.setPalette(palette)
        self.btnTarget.setObjectName("btnTarget")
        self.vloControls.addWidget(self.btnTarget)
        self.hloAll.addLayout(self.vloControls)
        self.vloCurves = QtWidgets.QVBoxLayout()
        self.vloCurves.setObjectName("vloCurves")
        self.hloCurveButtons = QtWidgets.QHBoxLayout()
        self.hloCurveButtons.setObjectName("hloCurveButtons")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hloCurveButtons.addItem(spacerItem1)
        self.btnClear = QtWidgets.QPushButton(self.centralwidget)
        self.btnClear.setObjectName("btnClear")
        self.hloCurveButtons.addWidget(self.btnClear)
        self.btnSeeAll = QtWidgets.QPushButton(self.centralwidget)
        self.btnSeeAll.setObjectName("btnSeeAll")
        self.hloCurveButtons.addWidget(self.btnSeeAll)
        self.btnPause = QtWidgets.QPushButton(self.centralwidget)
        self.btnPause.setObjectName("btnPause")
        self.hloCurveButtons.addWidget(self.btnPause)
        self.btnResetY = QtWidgets.QPushButton(self.centralwidget)
        self.btnResetY.setObjectName("btnResetY")
        self.hloCurveButtons.addWidget(self.btnResetY)
        self.btnResetX = QtWidgets.QPushButton(self.centralwidget)
        self.btnResetX.setObjectName("btnResetX")
        self.hloCurveButtons.addWidget(self.btnResetX)
        self.btnNow = QtWidgets.QPushButton(self.centralwidget)
        self.btnNow.setObjectName("btnNow")
        self.hloCurveButtons.addWidget(self.btnNow)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hloCurveButtons.addItem(spacerItem2)
        self.vloCurves.addLayout(self.hloCurveButtons)
        self.hloAll.addLayout(self.vloCurves)
        self.gridLayout.addLayout(self.hloAll, 0, 0, 1, 1)
        WindowMain.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WindowMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 892, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSignal_Sets = QtWidgets.QMenu(self.menubar)
        self.menuSignal_Sets.setObjectName("menuSignal_Sets")
        WindowMain.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WindowMain)
        self.statusbar.setObjectName("statusbar")
        WindowMain.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(WindowMain)
        self.actionExit.setObjectName("actionExit")
        self.actionSettings = QtWidgets.QAction(WindowMain)
        self.actionSettings.setObjectName("actionSettings")
        self.actionClosed_Loop = QtWidgets.QAction(WindowMain)
        self.actionClosed_Loop.setObjectName("actionClosed_Loop")
        self.actionCurrents = QtWidgets.QAction(WindowMain)
        self.actionCurrents.setObjectName("actionCurrents")
        self.actionTarget = QtWidgets.QAction(WindowMain)
        self.actionTarget.setObjectName("actionTarget")
        self.actionAdd_Signals = QtWidgets.QAction(WindowMain)
        self.actionAdd_Signals.setObjectName("actionAdd_Signals")
        self.menuFile.addAction(self.actionAdd_Signals)
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addAction(self.actionExit)
        self.menuSignal_Sets.addAction(self.actionClosed_Loop)
        self.menuSignal_Sets.addAction(self.actionCurrents)
        self.menuSignal_Sets.addAction(self.actionTarget)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSignal_Sets.menuAction())

        self.retranslateUi(WindowMain)
        QtCore.QMetaObject.connectSlotsByName(WindowMain)

    def retranslateUi(self, WindowMain):
        _translate = QtCore.QCoreApplication.translate
        WindowMain.setWindowTitle(_translate("WindowMain", "Dummy Window Title"))
        self.labelDrivers.setText(_translate("WindowMain", "Driver:"))
        self.labelSignals.setText(_translate("WindowMain", "Signal:"))
        self.labelAxis.setText(_translate("WindowMain", "Y-axis:"))
        self.rbAxis1.setText(_translate("WindowMain", "1"))
        self.rbAxis2.setText(_translate("WindowMain", "2"))
        self.rbAxis3.setText(_translate("WindowMain", "3"))
        self.btnAdd.setText(_translate("WindowMain", "Add Signal"))
        self.labelRemove.setText(_translate("WindowMain", "Remove:"))
        self.btnRemoveSel.setText(_translate("WindowMain", "Selected"))
        self.btnRemoveAll.setText(_translate("WindowMain", "All"))
        self.btnShift.setText(_translate("WindowMain", "Shift Y-axis"))
        self.btnCLoop.setText(_translate("WindowMain", "* Closed Loop *"))
        self.btnCurrents.setText(_translate("WindowMain", "* Currents *"))
        self.btnTarget.setText(_translate("WindowMain", "* Target *"))
        self.btnClear.setText(_translate("WindowMain", "Clear"))
        self.btnSeeAll.setText(_translate("WindowMain", "All Data"))
        self.btnSeeAll.setShortcut(_translate("WindowMain", "Ctrl+S"))
        self.btnPause.setText(_translate("WindowMain", "Pause"))
        self.btnResetY.setText(_translate("WindowMain", "Reset Y"))
        self.btnResetX.setText(_translate("WindowMain", "Reset X"))
        self.btnNow.setText(_translate("WindowMain", "Now"))
        self.menuFile.setTitle(_translate("WindowMain", "File"))
        self.menuSignal_Sets.setTitle(_translate("WindowMain", "Signal Sets"))
        self.actionExit.setText(_translate("WindowMain", "Exit"))
        self.actionExit.setShortcut(_translate("WindowMain", "Ctrl+X"))
        self.actionSettings.setText(_translate("WindowMain", "Settings"))
        self.actionClosed_Loop.setText(_translate("WindowMain", "Closed Loop"))
        self.actionCurrents.setText(_translate("WindowMain", "Currents"))
        self.actionTarget.setText(_translate("WindowMain", "Target"))
        self.actionAdd_Signals.setText(_translate("WindowMain", "Add Signals"))
        self.actionAdd_Signals.setShortcut(_translate("WindowMain", "Ctrl+A"))
